### ISSUE TITLE
Package is missing in 

### ISSUE THREAD

**Issue by mirrorps** [raoul2000/yii2-twbsmaxlength-widget#1]
Hi Raoul,

Looks like the package is not registered with packagist.org.

**Comment by raoul2000** [comment]
Hi mirrorps,

yes, I know ... I had no time to work on it lately but I will publish it soon.

**Comment by mirrorps** [comment]
Hi Raoul,

Thanks. Just to add this - I've tried to install it vie composer many times, but kept getting the same error about minimum stability issue (mine is set to stable), no matter of the package version & stability configuration I tried (I've made a custom config for the package in my project's composer.json file in repositories section).

**Comment by raoul2000** [comment]
Hi mirrorps,

I have release stable version 1.0.0 and register it to packagist. You should now be able to install it with no problem (hopefully).
