### ISSUE TITLE
Issue on tabular input

### ISSUE THREAD

**Issue by mirrorps** [raoul2000/yii2-twbsmaxlength-widget#2]
Hi Raoul,

This one does't work on tabular input since `$field->attribute` returns [index]FieldName:

``` php
$maxLength = static::getMaxLength($field->model, $field->attribute);
```

I've use it this way:

``` php
$maxLength = static::getMaxLength($field->model, Html::getAttributeName($field->attribute));
```

**Comment by raoul2000** [comment]
Hi mirrorps,

good catch. I will use your fix. 

Are you using the widget successfully ? did you encounter any issue to use it ?

**Comment by mirrorps** [comment]
Hi Raoul,

Yes, I'm using your widget successfully, it's really easy to be integrated and does a nice job. Congrats on that.

Something that bothers me a little is how the `TwbsMaxlength::apply` is used. May I suggest you to keep the Yii2 logic for using widgets like this:

``` php
$form->field($model, 'ModelField')->widget(TwbsMaxlength::className(), [
                    'threshold' => 100,
                    'preText' => Yii::t('app', 'You have') . ' ',
                    'separator' => ' ' . Yii::t('app', 'of') . ' ',
                    'postText' => ' ' . Yii::t('app', 'chars remaining.'),
                    'warningClass' => "label label-success",
                    'limitReachedClass' => "label label-danger",
]);
```

This way you can apply your widget to every input field following the common Yii2 code fashion and minimises the code needed for the widget to be used (for the case where you need to use a custom input field different from text). 

Thanks again for the widget.

**Comment by raoul2000** [comment]
Hi mirrorps,

the version 1.0.0 now includes the Yii2 logic to use the Widget, just like your suggestion. I've also fixed the attribute name issue with tabular input  

Version 1.0.0 is available at packagist.org

Thanks for your help and suggestions !

**Comment by mirrorps** [comment]
Hi raoul2000,

Thanks, you're welcome.
