### ISSUE TITLE
bootstrap-maxlength.js - error 404 (Not Found)

### ISSUE THREAD

**Issue by koxu1996** [raoul2000/yii2-twbsmaxlength-widget#4]
I installed your widget by composer and I was getting error:

> GET http://frontend.dev/assets/ee8c09e5/bootstrap-maxlength.js 404 (Not Found)

I fixed it by changing one line in TwbsMaxlengthAsset.php:

```
--- 'bootstrap-maxlength'.( YII_ENV_DEV ? '.js' : '.min.js' )
+++ 'src/bootstrap-maxlength'.( YII_ENV_DEV ? '.js' : '.min.js' )
```

I want also ask whether widget should render input without form-control class? I think not, but currently it works this way.

**Comment by raoul2000** [comment]
fixed, thanks
